replicaCount: 1

image:
  registry: 384511757320.dkr.ecr.us-east-1.amazonaws.com
  repository: dev-user-service
  tag: 2d229fb425365dd6fd2b51ba973419a2279a58a8
  pullPolicy: Always

# This is for setting up a service more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/
service:

  type: LoadBalancer
  port: 80
  targetPort: 5000
