replicaCount: 1

image:
  registry: 530467655811.dkr.ecr.us-east-1.amazonaws.com
  repository: dev-user-service
  tag: 3d45013a3ecc53d1181cd6f90206f0e31afb1749
  pullPolicy: Always

# This is for setting up a service more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/
service:

  type: LoadBalancer
  port: 80
  targetPort: 5000

ingress:
  enabled: true
  className: alb
  annotations: {}
  hosts:
    - host: user-service.dev.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
