replicaCount: 3

image:
  repository: uat-user-service

  pullPolicy: Always

  tag: latest

# This is for setting up a service more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/
service:

  type: LoadBalancer
  port: 80
  targetPort: 5000
