apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: user-service
  namespace: argocd

  annotations:
    argocd-image-updater.argoproj.io/image-list: user-service=530467655811.dkr.ecr.us-east-1.amazonaws.com/dev-user-service
    argocd-image-updater.argoproj.io/user-service.update-strategy: latest
    argocd-image-updater.argoproj.io/user-service.force-update: "true"

    argocd-image-updater.argoproj.io/user-service.helm.image-name: image.repository
    argocd-image-updater.argoproj.io/user-service.helm.image-tag: image.tag
spec:
  project: default
  source:
    repoURL: https://github.com/maheshsaini1997/DevOps-Platform
    targetRevision: HEAD
    path: helm/user-service
    helm:
      valueFiles:
      - values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: user-service-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
