name: CI Pipeline

on:
  push:
    paths:
      - 'application-microservices/**'

permissions:
  contents: write

jobs:

  detect-service:
    runs-on: ubuntu-latest

    outputs:
      services: ${{ steps.set.outputs.services }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Detect changed services
        id: set
        run: |
          CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})

          SERVICES=$(echo "$CHANGED_FILES" \
            | grep 'application-microservices/' \
            | cut -d'/' -f2 \
            | sort -u \
            | jq -R -s -c 'split("\n")[:-1]')

          echo "services=$SERVICES" >> $GITHUB_OUTPUT

  build-and-push:
    needs: detect-service

    if: needs.detect-service.outputs.services != '[]'

    strategy:
      matrix:
        service: ${{ fromJson(needs.detect-service.outputs.services) }}

    uses: ./.github/workflows/reusable-build.yaml

    with:
      service_name: ${{ matrix.service }}
      service_path: application-microservices/${{ matrix.service }}
      environment: dev


    secrets: inherit