name: Notification Service CI

on:
    push:
        branches: [ "main" ]
        paths:
            - 'application-microservices/notification-service/**'
    pull_request:
        branches: [ "main" ]
        paths:
            - 'application-microservices/notification-service/**'

jobs:
    build:
        uses: ./.github/workflows/reusable-build.yaml
        with:
            service_name: notification-service
            service_path: application-microservices/notification-service
        secrets: inherit