name: Payment Service CI

on:
    push:
        branches: [ "main" ]
        paths:
            - 'application-microservices/payment-service/**'
    pull_request:
        branches: [ "main" ]
        paths:
            - 'application-microservices/payment-service/**'

jobs:
    build:
        uses: ./.github/workflows/reusable-build.yaml
        with:
            service_name: payment-service
            service_path: application-microservices/payment-service
        secrets: inherit