name: Reusable Build

on:
  workflow_call:
    inputs:
      service_name:
        required: true
        type: string
      service_path:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set image tag
        run: echo "IMAGE_TAG=${{ github.sha }}" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          cd ${{ inputs.service_path }}
          docker build -t ${{ inputs.service_name }}:${{ env.IMAGE_TAG }} .

      - name: Print image info
        run: |
          echo "Build image: ${{ inputs.service_name }}:${{ env.IMAGE_TAG }}"