name: Terraform Pipeline

on:
  pull_request:
    paths:
      - 'terraform-infra/**'

  push:
    branches:
      - main
    paths:
      - 'terraform-infra/**'

jobs:

  # ================= DEV =================
  dev:
    runs-on: ubuntu-latest

    if: startsWith(github.ref_name, 'feature/') || github.ref_name == 'main'

    environment: dev

    defaults:
      run:
        working-directory: terraform-infra/environments/dev

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        if: github.ref_name == 'main'
        run: terraform apply -auto-approve


  # ================= TEST =================
  test:
    runs-on: ubuntu-latest

    needs: dev
    if: github.ref_name == 'main'

    environment: test

    defaults:
      run:
        working-directory: terraform-infra/environments/test

    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - run: terraform init
      - run: terraform validate
      - run: terraform plan
      - run: terraform apply -auto-approve


  # ================= UAT =================
  uat:
    runs-on: ubuntu-latest

    needs: test
    if: github.ref_name == 'main'

    environment: uat

    defaults:
      run:
        working-directory: terraform-infra/environments/uat

    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - run: terraform init
      - run: terraform validate
      - run: terraform plan
      - run: terraform apply -auto-approve


  # ================= PROD =================
  prod:
    runs-on: ubuntu-latest

    needs: uat
    if: github.ref_name == 'main'

    environment: prod

    defaults:
      run:
        working-directory: terraform-infra/environments/prod

    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - run: terraform init
      - run: terraform validate
      - run: terraform plan
      - run: terraform apply -auto-approve