name: User Service CI

on:
    push:
        branches: [ "main" ]
        paths:
            - 'application-microservices/user-service/**'
    pull_request:
        branches: [ "main" ]
        paths:
            - 'application-microservices/user-service/**'

jobs:
    build:
        uses: ./.github/workflows/reusable-build.yaml
        with:
            service_name: user-service
            service_path: application-microservices/user-service